In [23]:
# import libraries

%matplotlib notebook
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.dummy import DummyClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve, auc
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_recall_curve
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [37]:
# cargar la base dummyficada
df_dummy = pd.read_csv('C:/Users/Diego/OneDrive/Documents/GitHub/BD-ML---PS2/data/dfdummy.csv')
train_s = pd.read_csv('C:/Users/Diego/OneDrive/Documents/GitHub/BD-ML---PS2/data/train_s.csv')
test_s = pd.read_csv('C:/Users/Diego/OneDrive/Documents/GitHub/BD-ML---PS2/data/tets_s.csv')

,Unnamed: 0,Clase1,Clase2,P5000,P5010,P50902,P50903,P50904,P50905,P50906,...,prop_ocupados_pet,prop_Desocupados_pet,prop_mujeres_total,Ingtotugarr,recibe_arriendos1,prop_cotiza,ppc,Valor_Arriendo,age2,log_ingtot
0,135512,1,0,2.889175,2.238883,0,0,0,0,0,...,-0.246155,-0.378393,0.815288,7211667.0,1,1.311684,-0.877705,0.131180,1.775168,15.791211
1,38243,1,0,0.489637,1.125713,1,0,0,0,0,...,0.246213,-0.378393,-0.987154,3604000.0,0,1.070852,-0.475079,0.054949,-0.460446,15.097555
2,16786,1,0,0.489637,1.125713,0,0,0,0,0,...,-1.132417,0.802340,-0.446422,2850000.0,1,-0.277805,-0.072452,-0.021282,0.578765,14.862830
3,115046,1,0,0.489637,0.012543,0,0,1,0,0,...,-0.738523,-0.378393,-0.686747,1800000.0,0,-0.855801,-0.273766,0.004128,0.948456,14.403298
4,56742,1,0,2.089329,3.352053,0,0,0,0,0,...,0.049265,-0.378393,1.716510,6235269.0,1,1.456183,-0.636129,0.004128,2.423146,15.645732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131963,44190,1,0,-0.310209,0.012543,0,1,0,0,0,...,-0.246155,-0.378393,1.716510,1662676.0,0,0.589189,-0.877705,0.004128,-0.953561,14.323940
131964,111650,1,0,0.489637,-1.100627,0,0,0,0,0,...,-0.246155,-0.378393,1.716510,170833.3,0,-0.855801,0.330174,-0.122899,2.520372,12.048449
131965,82138,1,0,1.289483,1.125713,0,1,0,0,0,...,-0.879199,0.464988,0.815288,3975000.0,0,-0.442947,1.135427,0.105770,0.303971,15.195536
131966,135201,1,0,-1.110056,-1.100627,0,0,0,1,0,...,-0.246155,-0.378393,-0.085933,300000.0,0,-0.855801,2.745931,-0.046692,0.110102,12.611541
131967,32026,1,0,-0.310209,0.012543,0,1,0,0,0,...,0.246213,1.589495,0.514881,1480000.0,0,-0.855801,-0.273766,-0.008577,-0.013323,14.207553

In [40]:
train_s.head()
aux = np.sqrt(train_s.shape[1])
aux

10.63014581273465

In [ ]:
#train_s.head()
y_train = train_s['Pobre1']
x_train = train_s.drop(['Unnamed: 0','Pobre1','log_ingtot','Ingtotugarr','Clase1','Lp'], axis=1) 

# crear RandomForestClassifier
class_rfc = RandomForestClassifier()
grid_values = {'n_estimators': [2,3,5,10], 'max_features':[5,10,15], 'max_depth': [None, 10, 30], 'random_state': [0.7,0.8,0.9],  'criterion': ['gini', 'entropy']}
grid_rfc_recall = GridSearchCV(class_rfc, param_grid= grid_values, scoring='recall')
grid_rfc_recall.fit(x_train,y_train)

grid_rfc_recall


#X = df_scl_oe.drop(['price'], axis=1)